---
defaults:
  pulse:
    username: "..."
    password: "..."
  azure:
    accountName: "..."
    accountKey: "..."
verify:
  taskcluster:
    # These credentials must have the scopes:
    # * 'purge-cache:verifyprovisioner/verifyworker:verifycache'
    credentials:
      clientId: "..."
      accessToken: "..."
